apiVersion: skaffold/v1
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/*
build:
  local:
    push: false
  artifacts:
    - image: namankr301/burger_world_products
      context: Products
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: namankr301/burger_world_auth
      context: Auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: namankr301/burger_world_orders
      context: Orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: namankr301/burger_world_client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    