apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: namankr301/burger_world_cart
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom:
                  secretKeyRef:
                    name: cart-db
                    key: MONGODB_URI
            # - name: REDIS_HOST
            #   value: cart-redis-srv
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq-srv:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  selector:
    app: cart
  ports:
    - name: product
      protocol: TCP
      port: 3000
      targetPort: 3000