apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: namankr301/burger_world_products
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGODB_URI
              valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: MONGODB_URI
            - name: REDIS_HOST
              value: products-redis-srv
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: product
      protocol: TCP
      port: 3000
      targetPort: 3000